workflows:
  build:
    triggering:
      events:
        - pull_request
    name: Build
    environment:
      groups:
        - test_sec
      flutter: stable
    scripts:
      - name: Say Hello
        script: echo "No Hello World! $TEST_SEC1"
